### ISSUE TITLE
[EPIC] Plug-in integration approach

### ISSUE THREAD

**Issue by masaimu** [traas-stack/holoinsight#275]
### Refactor Request

Integrating new features or external systems through a plug-in approach, such as "Alert Hosting Plugin", "Slack Alert Notification Channel", "DingTalk Alert Notification Channel", etc.

- [ ] Alert hosting plugin
- [ ] DingTalk alert notification channel
- [ ] Slack alert notification channel
